//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Westeros
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGameTerritory
    {
        public long GameTerritoryID { get; set; }
        public long GameID { get; set; }
        public int TerritoryID { get; set; }
        public long TerritoryArmyID { get; set; }
    }
}
