//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Westeros
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHouseCard
    {
        public int HouseCardID { get; set; }
        public int HouseID { get; set; }
        public string HouseCardKey { get; set; }
        public string HouseCardDescription { get; set; }
        public int HouseCardTypeID { get; set; }
        public int HouseCardPower { get; set; }
    }
}
