//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Westeros
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHouse
    {
        public int HouseID { get; set; }
        public string Color { get; set; }
        public int StartingIronThronePosition { get; set; }
        public int StartingFiefdomPosition { get; set; }
        public int StartingFealtyPosition { get; set; }
    }
}
