//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Westeros
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPlayer
    {
        public long PlayerID { get; set; }
        public System.Guid UserID { get; set; }
        public long GameID { get; set; }
        public long HouseID { get; set; }
        public int IronThronePosition { get; set; }
        public int FiefdomPosition { get; set; }
        public int FealtyPosition { get; set; }
    }
}
