//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Westeros
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTerritory
    {
        public int TerritoryID { get; set; }
        public int SupplyCount { get; set; }
        public int TerritoryTypeID { get; set; }
    }
}
